services:

  creditguard-app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    container_name: creditguard-ai
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MODEL_VERSION=v1
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=creditguard
      - POSTGRES_USER=creditguard
      - POSTGRES_PASSWORD=creditguard
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    container_name: creditguard-minio
    command: server /data --console-address ":9001"
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc:latest
    container_name: creditguard-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb --ignore-existing local/raw-data &&
      mc mb --ignore-existing local/processed-data &&
      mc mb --ignore-existing local/model-artifacts &&
      echo 'Buckets criados com sucesso.'
      "

  postgres:
    image: postgres:16-alpine
    container_name: creditguard-postgres
    environment:
      - POSTGRES_DB=creditguard
      - POSTGRES_USER=creditguard
      - POSTGRES_PASSWORD=creditguard
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U creditguard"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio_data:
  postgres_data:
