FROM apache/airflow:2.10.0
USER root
RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 && rm -rf /var/lib/apt/lists/*
USER airflow
COPY requirements.airflow.txt /tmp/requirements.airflow.txt
RUN pip install --no-cache-dir -r /tmp/requirements.airflow.txt
