paths:
  raw_data:   Dados/raw/application_train.csv
  clean_data: Dados/clean_data.csv
  abt:        Dados/abt.csv
  medianas:   Model/artifacts/medianas.joblib

abt_features:
  - TARGET
  - AMT_INCOME_TOTAL
  - AMT_CREDIT
  - AMT_ANNUITY
  - AMT_GOODS_PRICE
  - DAYS_BIRTH
  - DAYS_EMPLOYED
  - CNT_CHILDREN
  - CNT_FAM_MEMBERS
  - FLAG_OWN_CAR
  - FLAG_OWN_REALTY
  - NAME_INCOME_TYPE
  - NAME_EDUCATION_TYPE
  - NAME_FAMILY_STATUS
  - NAME_HOUSING_TYPE
  - OCCUPATION_TYPE
  - ORGANIZATION_TYPE
  - EXT_SOURCE_1
  - EXT_SOURCE_2
  - EXT_SOURCE_3
  - REGION_POPULATION_RELATIVE
  - REGION_RATING_CLIENT
  - REGION_RATING_CLIENT_W_CITY
  - AMT_REQ_CREDIT_BUREAU_DAY
  - AMT_REQ_CREDIT_BUREAU_WEEK
  - AMT_REQ_CREDIT_BUREAU_MON
  - AMT_REQ_CREDIT_BUREAU_QRT
  - AMT_REQ_CREDIT_BUREAU_YEAR

bureau_cols:
  - AMT_REQ_CREDIT_BUREAU_DAY
  - AMT_REQ_CREDIT_BUREAU_WEEK
  - AMT_REQ_CREDIT_BUREAU_MON
  - AMT_REQ_CREDIT_BUREAU_QRT
  - AMT_REQ_CREDIT_BUREAU_YEAR

missing_flag_cols:
  - EXT_SOURCE_1
  - EXT_SOURCE_3

numeric_impute_cols:
  - EXT_SOURCE_1
  - EXT_SOURCE_2
  - EXT_SOURCE_3
  - AMT_GOODS_PRICE
  - AMT_ANNUITY
  - CNT_FAM_MEMBERS

minio:
  buckets:
    raw_data:       raw-data
    processed_data: processed-data
    artifacts:      model-artifacts
  objects:
    raw_data:   raw/application_train.csv
    clean_data: processed/clean_data.csv
    abt:        processed/abt.csv
    medianas:   medianas.joblib
