paths:
  raw_data:    Dados/raw/application_train.csv
  bureau_data: Dados/raw/bureau.csv
  clean_data:  Dados/clean_data.csv
  abt:         Dados/abt.csv

minio:
  buckets:
    raw_data:       raw-data
    processed_data: processed-data
    artifacts:      model-artifacts
  objects:
    raw_data:    raw/application_train.csv
    bureau_data: raw/bureau.csv
    clean_data:  processed/clean_data.csv
    abt:         processed/abt.csv
